-- Redirect existing reference records to unchanged raster assets now served from PostgreSQL.
UPDATE outfits SET thumbnail_url='/figure/female-layers/shirts/jade/thumbnail.png' WHERE code='AO_DAI';
UPDATE outfit_assets SET image_url='/figure/female-layers/shirts/jade/front.png' WHERE outfit_id=(SELECT id FROM outfits WHERE code='AO_DAI') AND asset_type='GARMENT';
UPDATE outfits SET thumbnail_url='/figure/female-layers/shirts/tu-than/thumbnail.png' WHERE code='AO_TU_THAN';
UPDATE outfit_assets SET image_url='/figure/female-layers/shirts/tu-than/front.png' WHERE outfit_id=(SELECT id FROM outfits WHERE code='AO_TU_THAN') AND asset_type='GARMENT';
UPDATE outfits SET thumbnail_url='/figure/female-layers/shirts/ngu-than/thumbnail.png' WHERE code='AO_NGU_THAN';
UPDATE outfit_assets SET image_url='/figure/female-layers/shirts/ngu-than/front.png' WHERE outfit_id=(SELECT id FROM outfits WHERE code='AO_NGU_THAN') AND asset_type='GARMENT';
UPDATE outfits SET thumbnail_url='/figure/female-layers/shirts/nhat-binh/thumbnail.png' WHERE code='NHAT_BINH';
UPDATE outfit_assets SET image_url='/figure/female-layers/shirts/nhat-binh/front.png' WHERE outfit_id=(SELECT id FROM outfits WHERE code='NHAT_BINH') AND asset_type='GARMENT';
UPDATE outfits SET thumbnail_url='/figure/female-layers/shirts/ba-ba/thumbnail.png' WHERE code='AO_BA_BA';
UPDATE outfit_assets SET image_url='/figure/female-layers/shirts/ba-ba/front.png' WHERE outfit_id=(SELECT id FROM outfits WHERE code='AO_BA_BA') AND asset_type='GARMENT';
UPDATE outfit_assets SET image_url='/figure/female-layers/body/front.png' WHERE asset_type='BASE_AVATAR';
UPDATE accessories SET image_url='/figure/female-layers/skirts/skirt-long-ivory/front.png' WHERE code='VAY_DUP';
UPDATE accessories SET image_url='/figure/female-layers/skirts/skirt-short-navy/front.png' WHERE code='VAY_XEP_LY';
UPDATE accessories SET image_url='/figure/female-layers/pants/ivory/front.png' WHERE code='QUAN_LUA';
UPDATE accessories SET image_url='/figure/female-layers/headwear/non-quai-thao/front.png' WHERE code='NON_QUAI_THAO';
UPDATE accessories SET image_url='/figure/female-layers/headwear/khan-mo-qua/front.png' WHERE code='KHAN_MO_QUA';
UPDATE accessories SET image_url='/figure/female-layers/headwear/khan-van/front.png' WHERE code='KHAN_VAN';
UPDATE accessories SET image_url='/figure/female-layers/headwear/khan-xep/front.png' WHERE code='KHAN_XEP';
UPDATE accessories SET image_url='/figure/female-layers/hair-accessories/hoa-cai-toc/front.png' WHERE code='HOA_CAI_TOC';
UPDATE accessories SET image_url='/figure/female-layers/jewelry/necklaces/kieng-bac/front.png' WHERE code='KIENG_BAC';
UPDATE accessories SET image_url='/figure/female-layers/jewelry/earrings/bong-tai/front.png' WHERE code='TRANG_SUC';
UPDATE accessories SET image_url='/figure/female-layers/shoes/guoc/front.png' WHERE code='GUOC';
UPDATE accessories SET image_url='/figure/female-layers/shoes/hai-theu/front.png' WHERE code='HAI_THEU';
UPDATE accessories SET image_url='/figure/female-layers/shoes/giay-bup-be/front.png' WHERE code='GIAY_BUP_BE';
UPDATE accessories SET image_url='/figure/female-layers/headwear/non-la/front.png' WHERE code='NON_LA';
UPDATE accessories SET image_url='/figure/female-layers/handheld/quat-giay/front.png' WHERE code='FAN';
UPDATE accessories SET image_url='/figure/female-layers/bags/tui-coi/front.png' WHERE code='MINIMAL_BAG';
UPDATE accessories SET image_url='/figure/female-layers/shoes/sneakers/front.png' WHERE code='WHITE_SNEAKERS';
