import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, CloudSun, MapPin, ShieldCheck, Sparkles } from 'lucide-react';
import { ChoiceGroup } from '../components/mix/Selectors';
import { ErrorBox, Loading, PageHeading, Stepper } from '../components/common/UI';
import { getWeather } from '../services/weatherApi';
import { recommend } from '../services/recommendationApi';
import { errorMessage } from '../services/api';
import { useSession } from '../state';
import type { Weather } from '../types';
export const events = [{code:'TET',label:'Tết'},{code:'FESTIVAL',label:'Lễ hội'},{code:'GRADUATION',label:'Kỷ yếu'},{code:'PHOTOSHOOT',label:'Chụp ảnh'}];
export const styles = [{code:'GEN_Z',label:'Gen Z'},{code:'MINIMAL',label:'Minimal'},{code:'ELEGANT',label:'Thanh lịch'},{code:'TRADITIONAL',label:'Truyền thống'}];
const colors = [{code:'RED',label:'Đỏ'},{code:'WHITE',label:'Trắng'},{code:'BLUE',label:'Xanh'},{code:'ANY',label:'Không quan trọng'}];
export const cities = [{code:'Hanoi',label:'Hà Nội'},{code:'Ho Chi Minh City',label:'TP. Hồ Chí Minh'},{code:'Da Nang',label:'Đà Nẵng'},{code:'Hue',label:'Huế'}];
const weatherLabels: Record<string, string> = { RAIN: 'Có mưa', SUNNY: 'Trời nắng', CLEAR: 'Trời quang', CLOUDS: 'Nhiều mây', CLOUDY: 'Nhiều mây', SNOW: 'Có tuyết' };
export default function StylistPage() {
  const { session, update } = useSession(); const previous = session.preferences; const navigate = useNavigate();
  const [eventCode,setEvent] = useState(previous?.eventCode || 'TET'); const [styleCode,setStyle] = useState(previous?.styleCode || 'GEN_Z'); const [colorCode,setColor] = useState(previous?.colorCode || 'RED'); const [city,setCity] = useState(previous?.city || 'Hanoi'); const [prompt,setPrompt] = useState(previous?.prompt || '');
  const [weather,setWeather] = useState<Weather>(); const [weatherError,setWeatherError] = useState(''); const [weatherRetry,setWeatherRetry] = useState(0); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  useEffect(()=>{const controller = new AbortController(); setWeather(undefined); setWeatherError(''); getWeather(city,controller.signal).then(data=>{if(!controller.signal.aborted)setWeather(data);}).catch(err=>{if(!controller.signal.aborted)setWeatherError(errorMessage(err));});return()=>controller.abort();},[city,weatherRetry]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if(!weather||busy)return; setBusy(true);setError('');const preferences={prompt:prompt.trim(),eventCode,styleCode,colorCode,city,weather};try{const recommendation=await recommend(preferences);if(!Array.isArray(recommendation.concepts)||recommendation.concepts.length!==3)throw new Error('Máy chủ chưa trả về đủ 3 concept. Vui lòng thử lại.');update({preferences,recommendation,mix:undefined});navigate('/concepts');}catch(err){setError(errorMessage(err));}finally{setBusy(false);} }
  return <main className="page-container"><Stepper active={0}/><PageHeading eyebrow="AI VIỆT STYLIST" title="Bắt đầu từ cảm hứng của bạn." description="Bạn kể một chút. AI gợi ý một chút. Cùng tìm ra outfit mang dấu ấn riêng."/><div className="stylist-layout"><form className="panel stylist-form" onSubmit={submit}><div className="panel-heading"><span className="icon-tile"><Sparkles size={22}/></span><div><h2>Hôm nay bạn muốn thế nào?</h2><p>Chọn nhanh hoặc viết điều bạn đang nghĩ.</p></div></div><ChoiceGroup label="01 — Bạn mặc vào dịp nào?" options={events} value={eventCode} onChange={setEvent} disabled={busy}/><ChoiceGroup label="02 — Phong cách của bạn" options={styles} value={styleCode} onChange={setStyle} disabled={busy}/><ChoiceGroup label="03 — Gam màu yêu thích" options={colors} value={colorCode} onChange={setColor} disabled={busy}/><div className="location-field"><label htmlFor="city"><MapPin size={17}/> Bạn đang ở đâu?</label><select id="city" value={city} onChange={e=>setCity(e.target.value)} disabled={busy}>{cities.map(c=><option key={c.code} value={c.code}>{c.label}</option>)}</select></div><div className="prompt-field"><label htmlFor="prompt">Hoặc, kể chi tiết hơn một chút <span>Không bắt buộc</span></label><textarea id="prompt" maxLength={1500} rows={4} value={prompt} disabled={busy} onChange={e=>setPrompt(e.target.value)} placeholder="Mình muốn mặc Việt phục đi chơi Tết, thích màu đỏ nhưng không quá nổi, phong cách trẻ trung…"/><div className="char-count">{prompt.length}/1500</div></div>{error&&<ErrorBox message={error}/>}<button className="button primary full-width" disabled={busy||!weather} type="submit"><Sparkles size={18}/>{busy?'AI đang tìm cảm hứng…':'Tạo 3 concept cho tôi'}{!busy&&<ArrowRight size={18}/>}</button><p className="form-note">Gợi ý dựa trên sở thích và thời tiết thực tế của bạn.</p></form><aside className="stylist-aside"><div className="weather-card"><div className="eyebrow"><CloudSun size={17}/> THỜI TIẾT NƠI BẠN</div><h3>{cities.find(c=>c.code===city)?.label}</h3>{weather?<><div className="temperature">{Math.round(weather.temperature)}<span>°C</span><CloudSun size={50} strokeWidth={1}/></div><p>{weatherLabels[weather.condition]||weather.condition}</p><div className="weather-bottom">Độ ẩm <strong>{weather.humidity}%</strong></div><small>Thời tiết sẽ được gửi cùng nhu cầu để AI gợi ý phù hợp.</small></>:weatherError?<ErrorBox message={weatherError} retry={()=>setWeatherRetry(v=>v+1)}/>:<Loading text="Đang lấy thời tiết thực tế…"/>}</div><div className="tip-card"><span className="decor-star">✳</span><h3>Không chỉ là<br/>một bộ trang phục.</h3><p>Mỗi Việt phục có một câu chuyện. Khám phá nguồn gốc, ý nghĩa và cách phối trong từng concept.</p><div><ShieldCheck size={18}/> Sáng tạo cùng sự thấu hiểu</div></div></aside></div></main>;
}
