import AssessmentDetails from './AssessmentDetails';
import { ArrowUpRight, Check, ShieldCheck, TriangleAlert } from 'lucide-react';
import type { Changes, CulturalResult } from '../../types';
import { ErrorBox, Loading } from '../common/UI';
const criteria = [{key:'structure',label:'Cấu trúc'}, {key:'garmentCharacteristics',label:'Đặc trưng áo'}, {key:'accessories',label:'Phụ kiện'}, {key:'context',label:'Bối cảnh'}, {key:'modernRemix',label:'Cách tân'}] as const;
const categoryLabels:Record<string,string> = {STRUCTURE:'Cấu trúc',GARMENT_CHARACTERISTICS:'Đặc trưng áo',ACCESSORIES:'Phụ kiện',CONTEXT:'Bối cảnh',MODERN_REMIX:'Cách tân'};
const levelLabels: Record<string, string> = { INSUFFICIENT_DATA: 'Chưa đủ dữ liệu văn hóa', WELL_PRESERVED: 'Giữ gìn tốt', SUITABLE: 'Phù hợp', SAFE: 'Hài hòa với văn hóa', GOOD: 'Hài hòa với văn hóa', WARNING: 'Có điểm cần lưu ý', DANGER: 'Cần điều chỉnh', HIGH_RISK: 'Cần điều chỉnh' };
export default function CulturalScore({ result, busy, error, retry, apply, disabled }: { result?: CulturalResult; busy: boolean; error: string; retry: ()=>void; apply: (changes: Changes)=>void; disabled?: boolean }) {
  return <aside className="panel cultural-panel"><div className="small-panel-heading"><ShieldCheck size={20}/><h2>Cultural Check</h2></div><p className="muted">Sáng tạo, cùng sự thấu hiểu.</p>{busy?<Loading text="Đang kiểm tra bản phối…"/>:error?<ErrorBox message={error} retry={retry}/>:result?<><div className={`score-circle ${result.level==='WARNING'||result.level==='DANGER'||result.level==='HIGH_RISK'?'warning':''}`} style={{'--score':`${Math.max(0,Math.min(100,result.score ?? 0))*3.6}deg`} as React.CSSProperties}><div><strong>{result.score ?? '—'}{result.score !== null && <small>%</small>}</strong><span>Cultural Score</span></div></div><div className="score-level">{levelLabels[result.level]||result.level}</div>{result.breakdown&&<dl className="cultural-breakdown">{criteria.map(item=><div key={item.key}><dt>{item.label}</dt><dd>{result.breakdown?.[item.key] ?? '—'}<small>/100</small></dd></div>)}</dl>}{result.explanation&&<p className="form-note cultural-check-detail" role="status">{result.explanation}</p>}<AssessmentDetails result={result}/>{result.warnings.length===0?<div className="check-success"><Check size={18}/> {result.score === null ? 'Chưa đủ quy tắc tham khảo để kết luận về bản phối.' : 'Máy chủ không ghi nhận cảnh báo cho bản phối này.'}</div>:<div className="warnings">{result.warnings.map((warning,i)=><article key={`${warning.category}-${i}`}><div><TriangleAlert size={17}/><strong>{categoryLabels[warning.category] || warning.category}</strong><small>{warning.severity}</small></div><p>{warning.message}</p>{warning.sourceUrl && /^https?:\/\//i.test(warning.sourceUrl) && <a className="source-link" href={warning.sourceUrl} target="_blank" rel="noopener noreferrer">{warning.sourceVerified ? 'Nguồn đối chiếu' : 'Tham khảo về trang phục'}: {warning.sourceName || 'Xem nguồn'}<ArrowUpRight size={14}/></a>}{warning.sourceNote && <p className="muted">{warning.sourceNote}</p>}<div className="suggestion"><b>Gợi ý dành cho bạn</b><p>{warning.suggestion}</p>{warning.changes&&<button disabled={disabled} className="text-button" onClick={()=>apply(warning.changes!)}>Áp dụng gợi ý →</button>}</div></article>)}</div>}</>:<p className="muted">Chọn một bản phối để bắt đầu kiểm tra.</p>}<div className="cultural-note"><ShieldCheck size={15}/><span>Điểm phản ánh bộ quy tắc tham khảo. Gợi ý phối đồ không phải quy định văn hóa bắt buộc.</span></div></aside>;
}
